theme = "lynx"
title = "na Bio"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "Sapiens"
  headline = "Agência Experimental de Publicidade e Propaganda"
  image = "author.jpg"
  links = [
    { link = { href = "https://sapienstj.com.br/seletiva", text = "Faça sua inscrição" } },  
    { blog = { href = "https://blog.sapienstj.com.br/", text = "Blog da Sapiens" } },
    { tom = { href = "https://tominformativo.sapienstj.com.br/", text = "Jornal Tom Informativo" } },
    { instagram = "https://instagram.com/sapienstj/" },
    { link = { href = "https://sapienstj.com.br/seletiva", text = "Confira nosso site" } },  
    { email = { href = "mailto:sapienstjatendi@gmail.com", text = "Fale conosco" } },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true

baseURL = "https://links.sapienstj.com.br/"
languageCode = "pt"
defaultContentLanguage = "pt"

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
